version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./dist:/usr/share/nginx/html
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.typeformfront.entrypoints=websecure"
      - "traefik.http.routers.typeformfront.rule=Host(`typeform.leod1.fr`)"
      - "traefik.http.routers.typeformfront.tls=true"
      - "traefik.http.routers.typeformfront.tls.certresolver=letsencrypt"
      - "traefik.docker.network=default"
    networks:
      - default


networks:
  default:
    external:
      name: gateway
